#!/bin/bash
 
NAME="yoolotto" # Name of the application
DJANGODIR=/home/ubuntu/current/yobackend/yoolotto # Django project directory 
SOCKFILE=/home/ubuntu/current/yobackend/yoolotto/deploy/gunicorn.sock # we will communicte using this unix socket
#USER=yoolotto # the user to run as
#GROUP=backend # the group to run as
NUM_WORKERS=3 # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=yoolotto.settings # which settings file should Django use
DJANGO_WSGI_MODULE=yoolotto.wsgi # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/ubuntu/current/yobackend/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
#--user=$USER --group=$GROUP \
--log-level=debug \
--bind 127.0.0.1:8000 \
--timeout=300
